Fix ReferenceError
After shutting down the Redis master, the following error was reported in the console:

ReferenceError: host is not defined
     ERR     at Command.callback (node_modules/redis-sentinel/index.js:37:31)

Thus I have removed the callback from the pubsubClient.subscribe("+switch-master") function and added a console output to pubsubClient.on("error") instead.

Tested with Node.js 0.10.33 and Redis 2.8.19.